name: Update Visitors
on:
  workflow_dispatch: {}
  schedule:
    # Summer (CEST, UTC+2): 00:00 Madrid = 22:00 UTC
    - cron: '0 22 * 4-10 *'
    # Winter (CET, UTC+1): 00:00 Madrid = 23:00 UTC
    - cron: '0 23 * 11,12,1,2,3 *'
  push:
    branches: [ main ]
    paths:
      - "README.md"
      - ".github/workflows/update-visitors.yml"
      - ".github/scripts/build-visitors-svg.js"

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build visitors.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: node .github/scripts/build-visitors-svg.js

      - name: Commit & push if changed
        run: |
          git config user.name  "actions-bot"
          git config user.email "actions@users.noreply.github.com"
          git add assets/visitors.svg assets/visitors-history.json
          git diff --staged --quiet || git commit -m "chore: update visitors svg"
          git push
