name: Update Achievements Slider

on:
  workflow_dispatch: {}
  schedule:
    # Summer (CEST, UTC+2): 00:00 Madrid = 22:00 UTC
    - cron: '0 22 * 4-10 *'
    # Winter (CET, UTC+1): 00:00 Madrid = 23:00 UTC
    - cron: '0 23 * 11,12,1,2,3 *'
  push:
    branches: [ main ]
    paths:
      - "README.md"
      - ".github/workflows/update-achievements.yml"
      - ".github/scripts/fetch-achievements.js"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm init -y
          npm install puppeteer@22.15.0

      - name: Run fetch-achievements
        env:
          GH_USERNAME: "pablobuza014"
          README_PATH: "README.md"
        run: node .github/scripts/fetch-achievements.js

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git diff --quiet && echo "No changes" || git commit -m "chore: update achievements slider"
          git push
